/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/account` | `/account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/orders` | `/orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/schedule` | `/schedule`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/about` | `/profile/about`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/addresses` | `/profile/addresses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/help-support` | `/profile/help-support`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/notifications` | `/profile/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/payment-methods` | `/profile/payment-methods`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/personal-info` | `/profile/personal-info`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/account` | `/account`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/orders` | `/orders`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/schedule` | `/schedule`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile/about` | `/profile/about`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile/addresses` | `/profile/addresses`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile/help-support` | `/profile/help-support`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile/notifications` | `/profile/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile/payment-methods` | `/profile/payment-methods`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile/personal-info` | `/profile/personal-info`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/account${`?${string}` | `#${string}` | ''}` | `/account${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/orders${`?${string}` | `#${string}` | ''}` | `/orders${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/schedule${`?${string}` | `#${string}` | ''}` | `/schedule${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile/about${`?${string}` | `#${string}` | ''}` | `/profile/about${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile/addresses${`?${string}` | `#${string}` | ''}` | `/profile/addresses${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile/help-support${`?${string}` | `#${string}` | ''}` | `/profile/help-support${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile/notifications${`?${string}` | `#${string}` | ''}` | `/profile/notifications${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile/payment-methods${`?${string}` | `#${string}` | ''}` | `/profile/payment-methods${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile/personal-info${`?${string}` | `#${string}` | ''}` | `/profile/personal-info${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/account` | `/account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/orders` | `/orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/schedule` | `/schedule`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/about` | `/profile/about`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/addresses` | `/profile/addresses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/help-support` | `/profile/help-support`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/notifications` | `/profile/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/payment-methods` | `/profile/payment-methods`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/personal-info` | `/profile/personal-info`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
