/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/orders` | `/orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/schedule` | `/schedule`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/account/about` | `/account/about`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/account/addresses` | `/account/addresses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/account/help-support` | `/account/help-support`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/account` | `/account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/account/notifications` | `/account/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/account/payment-methods` | `/account/payment-methods`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/account/personal-info` | `/account/personal-info`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/orders` | `/orders`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/schedule` | `/schedule`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/account/about` | `/account/about`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/account/addresses` | `/account/addresses`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/account/help-support` | `/account/help-support`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/account` | `/account`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/account/notifications` | `/account/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/account/payment-methods` | `/account/payment-methods`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/account/personal-info` | `/account/personal-info`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/orders${`?${string}` | `#${string}` | ''}` | `/orders${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/schedule${`?${string}` | `#${string}` | ''}` | `/schedule${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/account/about${`?${string}` | `#${string}` | ''}` | `/account/about${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/account/addresses${`?${string}` | `#${string}` | ''}` | `/account/addresses${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/account/help-support${`?${string}` | `#${string}` | ''}` | `/account/help-support${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/account${`?${string}` | `#${string}` | ''}` | `/account${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/account/notifications${`?${string}` | `#${string}` | ''}` | `/account/notifications${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/account/payment-methods${`?${string}` | `#${string}` | ''}` | `/account/payment-methods${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/account/personal-info${`?${string}` | `#${string}` | ''}` | `/account/personal-info${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/orders` | `/orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/schedule` | `/schedule`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/account/about` | `/account/about`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/account/addresses` | `/account/addresses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/account/help-support` | `/account/help-support`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/account` | `/account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/account/notifications` | `/account/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/account/payment-methods` | `/account/payment-methods`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/account/personal-info` | `/account/personal-info`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
